project/website/views.py
from flask import Blueprint, render_template, redirect, session, url_for, request
from website import database
from sqlalchemy import column, text

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template("home.html")


@views.route('/adminHome')
def adminHome():
    # Get the queries for the tables done
    userStatement = (f'SELECT * FROM ONLINE_AUCTION.User;')
    itemStatement = (f'SELECT * FROM ONLINE_AUCTION.Item;')

    userQuery = database.db.session.execute(text(userStatement)).all()
    itemQuery = database.db.session.execute(text(itemStatement)).all()

    # The tuples for passing the date to html
    # Turn the queries into tuples
    userData = tuple(userQuery)
    itemData = tuple(itemQuery)

    userHeadings = ("ID", "Name", "Email", "Password", "Phone Num", "Home Address", "Is Active")
    itemHeadings = ("ID", "Name", "Description", "Photo", "Starting Bid", "Bid Increment", "Start Date", "End Date")

    return render_template("adminHome.html", userHeadings=userHeadings, itemHeadings=itemHeadings, userData=userData, itemData=itemData)

@views.route('/adminDeleteUserPage', methods=['GET', 'POST'])
def adminDeleteUserPage():
    # Get the queries for the tables done
    userStatement = (f'SELECT * FROM ONLINE_AUCTION.User;')

    userQuery = database.db.session.execute(text(userStatement)).all()

    # The tuples for passing the date to html
    # Turn the queries into tuples
    userData = tuple(userQuery)

    userHeadings = ("ID", "Name", "Description", "Photo", "Starting Bid", "Bid Increment", "Start Date", "End Date")

    if request.method == "POST":
        try:
            if request.form['id']:
                user_id = request.values.get('id')
                user_id = int(user_id)
                statement = (f'UPDATE ONLINE_AUCTION.User SET IsActive = 0 WHERE UserID={ user_id };')
                database.db.session.execute(text(statement))
                database.db.session.commit()

                # Redo query for users to show that user has been successfully deleted
                userQuery = database.db.session.execute(text(userStatement)).all()

                # The tuples for passing the date to html
                # Turn the queries into tuples
                userData = tuple(userQuery)

                return render_template("adminDeleteUserPage.html", userHeadings=userHeadings, userData=userData, info="Successfully Deleted user")

            else:
                return render_template("adminDeleteUserPage.html", userHeadings=userHeadings, userData=userData)

        except Exception as e:
            print(e)
            return render_template("adminDeleteUserPage.html", userHeadings=userHeadings, userData=userData, info="Failed to Delete user")

    # Simply render the page
    if request.method == "GET":
        return render_template("adminDeleteUserPage.html", userHeadings=userHeadings, userData=userData, info="No Entered Item")

@views.route('/adminDeleteItemPage', methods=['GET', 'POST'])
def adminDeleteItemPage():
    # Get the queries for the tables done
    itemStatement = (f'SELECT * FROM ONLINE_AUCTION.Item;')

    itemQuery = database.db.session.execute(text(itemStatement)).all()

    # The tuples for passing the date to html
    # Turn the queries into tuples
    itemData = tuple(itemQuery)

    itemHeadings = ("ID", "Name", "Description", "Photo", "Starting Bid", "Bid Increment", "Start Date", "End Date")

    if request.method == "POST":
        try:
            if request.form['id']:
                user_id = request.values.get('id')
                user_id = int(user_id)
                statement = (f'DELETE FROM ONLINE_AUCTION.Item WHERE ItemID = {user_id};')
                database.db.session.execute(text(statement))
                database.db.session.commit()

                # Redo query for items to show that item has been successfully deleted
                itemQuery = database.db.session.execute(text(itemStatement)).all()

                # The tuples for passing the date to html
                # Turn the queries into tuples
                itemData = tuple(itemQuery)

                return render_template("adminDeleteItemPage.html", itemHeadings=itemHeadings, itemData=itemData, info="Successfully Deleted item")

            else:
                return render_template("adminDeleteItemPage.html", itemHeadings=itemHeadings, itemData=itemData, info="No Entered Item")

        except Exception as e:
            print(e)
            return render_template("adminDeleteItemPage.html", itemHeadings=itemHeadings, itemData=itemData, info="Failed to Delete item")

    # Simply render the page
    if request.method == "GET":
        return render_template("adminDeleteItemPage.html", itemHeadings=itemHeadings, itemData=itemData)

project/website/templates/adminDeleteItemPage.html
{% extends "base.html" %} {% block title %}adminDeleteItem{% endblock %}
{% block content %}
  <h1> Admin Delete Item Page </h1>

  {% if info %}
  <div>{{ info }}</div>
  {% endif %}

  <h3> Item Table </h3>
  <div style="">
    <div style="height:150px;overflow:auto;">
      <table style="">
        <thead style="">
          <tr>
            {% for header in itemHeadings %}
            <th style="text-align:center;">{{ header }}</th>
            {% endfor %}
          </tr>
        </thead>
        {% for row in itemData %}
        <tr>
          {% for cell in row %}
            <td style="text-align:center;background:#e5e5e5;">{{ cell }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <form style="margin-top:20px;" method="POST">
    <label for="id">ID of Item to Delete</label><br>
    <input type="id" pattern="[0-9]+" id="id" name="id"><br><br>
    <input type="submit" value="Delete Item">
  </form>

{% endblock %}

project/website/templates/adminDeleteUserPage.html
{% extends "base.html" %} {% block title %}adminDeleteUser{% endblock %}
{% block content %}
  <h1> Admin Delete User Page </h1>

  {% if info %}
  <div>{{ info }}</div>
  {% endif %}

  <h3> User Table </h3>
  <div style="">
    <div style="height:150px;overflow:auto;">
      <table style="">
        <thead style="">
          <tr>
            {% for header in userHeadings %}
            <th style="text-align:center;">{{ header }}</th>
            {% endfor %}
          </tr>
        </thead>
        {% for row in userData %}
        <tr>
          {% for cell in row %}
            <td style="text-align:center;background:#e5e5e5;">{{ cell }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <form style="margin-top:20px;" method="POST">
    <label for="id">ID of User to Deactivate</label><br>
    <input type="text" pattern="[0-9]+" id="id" name="id"><br><br>
    <input type="submit" value="Deactivate User">
  </form>

{% endblock %}

project/website/templates/adminHome.html
{% extends "base.html" %} {% block title %}AdminHome{% endblock %}
{% block content %}
  <h1> Admin Home Page </h1>

  <h3> User Table </h3>
  <div style="">
    <div style="height:150px;overflow:auto;">
      <table style="">
        <thead style="">
          <tr>
            {% for header in userHeadings %}
            <th style="text-align:center;">{{ header }}</th>
            {% endfor %}
          </tr>
        </thead>
        {% for row in userData %}
        <tr>
          {% for cell in row %}
            <td style="text-align:center;background:#e5e5e5;">{{ cell }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <h3 style="margin-top:20px;"> Item Table </h3>
  <div style="">
    <div style="height:150px;overflow:auto;">
      <table style="">
        <thead style="">
          <tr>
            {% for header in itemHeadings %}
            <th style="text-align:center;">{{ header }}</th>
            {% endfor %}
          </tr>
        </thead>
        {% for row in itemData %}
        <tr>
          {% for cell in row %}
            <td style="text-align:center;background:#e5e5e5;">{{ cell }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <div>
    <form action="{{ url_for('views.adminDeleteUserPage') }}" method="get"><button>Deactivate User</button></form>
    <form action="{{ url_for('views.adminDeleteItemPage') }}" method="get"><button>Deactivate Item</button></form>
  </div>
{% endblock %}

project/website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link
            rel="stylesheet"
            href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
            integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
            crossorigin="anonymous">

    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg" style="background-color: #0e495b;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="/">Online Auction</a>
        {% if session['login.id'] is defined %}
            <form class="form-inline my-2 my-lg-0" methods='POST' action='/search/'>
                <select name="category" id="category" class="form-control form-select form-select-sm my-1 mr-2"
                        aria-label="searchDropdownDescription .form-select-lg example">
                    <option value="All">All</option>
                    {% for category in categories %}
                    <option value="{{ category }}">{{ category }}</option>
                    {% endfor %}
                </select>
                <input class="form-control mr-sm-2 my-1" type="search" placeholder="Search an item"
                       aria-label="Search" id='query' name='query'>
                <button class="btn btn-outline-success my-1 my-sm-0" type="submit">Search</button>
            </form>
        {% endif %}
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" id="home" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if session['login.id'] is not defined %}
                <li class="nav-item">
                    <a class="nav-link" id="login" href="/login">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="sign_up" href="/sign_up">Sign Up</a>
                </li>
            {% else %}
                {% if session['login.type'] == 'seller' %}
                    <li class="nav-item active">
                        <a class="nav-link" id="sell" href="/sell">Sell</a>
                    </li>
                {% endif %}
                {% if session['login.type'] == 'admin' %}
                    <li class="nav-item active">
                        <a class="nav-link" id="sell" href="/adminHome">Admin</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" id="profile" href="/profile/{{ session['login.id'] }}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="logout" href="/logout">Logout</a>
                </li>
                {% if session['login.name'] %}
                    <li class="nav-item">
                        <a class="nav-link disabled" id="welcome" href="#">Welcome {{ session['login.name'] }}</a>
                    </li>
                {% endif %}
            {% endif %}

        </ul>
    </div>
</nav>


<div class="container py-4">{% block content %} {% endblock %}</div>

{% block script %} {% endblock %}
<script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>

<script
        type="text/javascript"
        src="{{ url_for('static', filename='index.js') }}"

></script>
</body>

<footer class="text-center text-white pt-2" style="background-color: #0e495b;">
    <!-- Grid container -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Online Auction
                    </h6>
                    <p>
                        We are the leading company for online bidding of used and new items.
                    </p>
                </div>
                <!-- Grid column -->


                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Office Address
                    </h6>
                    <p>
                        800 W Campbell Road, <br>
                        Richardson, TX 75080
                    </p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                    <!-- Links -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Contact
                    </h6>
                    <p>
                        <i class="fas fa-envelope me-3"></i>
                        support@onlineauction.com
                    </p>
                    <p><i class="fas fa-phone me-3"></i> + 01 478 888 9999</p>
                </div>
                <!-- Grid column -->
            </div>
            <!-- Grid row -->
        </div>
    </section>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: #024459;"
    ">
    © 2021 Copyright: Online Auction
    </div>
    <!-- Copyright -->
</footer>
</html>

project/website/templates/edit_profile.html
{% extends "base.html" %} {% block title %}{{ user['name'] }}{% endblock %}
{% block content %}
    <h1>Editing {{ user['name-noedit'] }}'s Profile</h1>
    {% if info %}
        <div>{{ info }}</div>
    {% endif %}

    <form>
        <label for="phone">Phone Number (10 digits, no dash):</label><br>
        <input type="tel" id="phone" name="phone" value="{{ user['phone'] }}" pattern="\d{10}" required><br><br>

        <label for="address">Home Address:</label><br>
        <input type="text" id="address" name="address" value="{{ user['address'] }}" required><br><br>

        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" value="{{ user['email'] }}" required><br><br>

        {% if user['type-noedit'] == 'buyer' %}
            <label for="shipping-address">Shipping Address:</label><br>
            <input type="text" id="shipping-address" name="shipping-address" value="{{ user['shipping-address'] }}"
                   required><br><br>

            <label for="city">City:</label><br>
            <input type="text" id="city" name="city" value="{{ user['city'] }}" required><br><br>
        {% endif %}

        {% if user['type-noedit'] == 'seller' %}
            <label for="account-num">Account Number (5-17 digits):</label><br>
            <input type="text" id="account-num" name="account-num" value="{{ user['account-num'] }}" pattern="\d{5,17"
                   required><br><br>

            <label for="routing-num">Routing Number (9 digits):</label><br>
            <input type="text" id="routing-num" name="routing-num" value="{{ user['routing-num'] }}" pattern="\d{9}"
                   required><br><br>
        {% endif %}

        <label for="edit-password">Confirm changes with your password:</label><br>
        <input type="password" id="edit-password" name="edit-password" required><br><br>

        <input type="submit" value="Done editing">
    </form>
{% endblock %}

project/website/templates/error.html
{% extends "base.html" %} {% block title %}Error{% endblock %}
{% block content %}
    <h1>An error has occurred.</h1>
    {% if error %}
    <p>{{ error }}</p>
    {% endif %}
{% endblock %}

project/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content %}
  <div class="container mt-3">
    <div>
      <img src="../static/images/HolidayBanner.jpg" class="img-fluid" alt="Responsive image">
    </div>
    <div class="row mt-2">
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Buyer</h5>
            <p class="card-text">A Buyer account can bid for items in the auction.</p>
            <a href="http://127.0.0.1:5000/sign_up" class="btn btn-primary">Create a Buyer Account</a>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Seller</h5>
            <p class="card-text">A Seller account can put items up for auction.</p>
            <a href="http://127.0.0.1:5000/sign_up" class="btn btn-primary">Create a Seller Account</a>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Admin</h5>
            <p class="card-text">Admins help manage the website and users.</p>
            <a href="#" class="btn btn-primary">Create an Admin Account</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

project/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <h1>Welcome!</h1>
    {% if info %}
        <div>{{ info }}</div>
    {% endif %}
    <form>
        <label for="id">Member ID:</label><br>
        <input type="text" pattern="[0-9]+" id="id" name="id"><br><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password"><br><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

project/website/templates/product_detail.html
{% extends "base.html" %} {% block title %}Product Detail{% endblock %} 
{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %} {% for category, message in messages %} {% if category ==
  'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
     
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}

    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endif %} {% endfor %} {% endif %} {% endwith %}

  <div class="container-fluid">
    <div class="row no-gutters">
      <div class="col-xl-8 margin-3">
                    <img src="{{ prod.Photo }}" class="img-fluid rounded " width ="600" alt="Preview Image">        
      </div>
      <div class="col-xl-4">
        <h4> <strong>{{ prod.Name }} </strong> </h4>
        <div class="table-responsive">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Item ID</strong></th>
                <td> {{ prod.ItemID }}</td>
              </tr>

              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Description</strong></th>
                <td> {{ prod.Description }}</td>
              </tr>

              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Sold By</strong></th>
                <td> <a href="/profile/{{ prod.SellerID}}" data-toggle="tooltip" data-placement="right" title="Click to view Reviews"> {{ seller.Name }} </a>

                  
                </td>
                
              </tr>
              {% if seller.Feedback %}
              <tr>
                <th></th>
                <td>
                  {% for i in range(0, seller.Feedback | int )%}
                    <span class="fa fa-star" style=" color: yellow;"></span>
                  {% endfor %}
                  {% for i in range(seller.Feedback | int, 10) %}
                    <span class="fa fa-star"></span>
                  {% endfor %}
                </td>
                
              </tr>
              {% endif %}
              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Start Date</strong></th>
                <td> {{ prod.StartDate }}</td>
              </tr>

              <tr>
                <th class="pl-0 w-25" scope="row"><strong>End Date</strong></th>
                <td> {{ prod.EndDate }}</td>
              </tr>
              
              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Starting Bid</strong></th>
                <td> {{ "$%.2f" | format(prod.StartingBid| float) }}</td>
              </tr>
              <tr>
                <th class="pl-0 w-25" scope="row"><strong>Bid Increment</strong></th>
                <td> {{ "$%.2f" | format(prod.BidIncrement| float) }}</td>
              </tr>
              
              {% if is_Feedback %}
              <tr>
                <td colspan="4">
                  <p><strong>Please Enter Following Feedback </strong></p>
                </td>
              </tr>
              <tr>
                {% if is_buyer %}
                  <td colspan="4"><strong>Feedback For Seller : </strong> {{bid_details.SellerID }}</td>
                {% else %}
                  <td colspan="4"><strong>Feedback For Buyer : </strong> {{ bid_details.BuyerID }}</td>
                {% endif %}
              </tr>
                  <form method='POST' action="/feedback/{{ bid_details.SellerID }}/{{ bid_details.BuyerID}}/{{ bid_details.ItemID }}">
                    {% if is_buyer %}
                    <tr>
                      <td colspan="4"> 
                        <div class="form-group">
                          <label for="seller_comment">Enter Feedback</label>
                          <textarea class="form-control" id="seller_comment" name='seller_comment'></textarea>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="4">
                        <div class="form-group">
                          <label for="seller_rating">Rating</label>
                          <select id="seller_rating" class="form-control" name='seller_rating'>
                            <option selected>10</option>
                            <option>9</option>
                            <option>8</option>
                            <option>7</option>
                            <option>6</option>
                            <option>5</option>
                            <option>4</option>
                            <option>3</option>
                            <option>2</option>
                            <option>1</option>
                          </select>
                        </div>
                      </td>
                    </tr>
                    {% else %}
                    <tr>
                      <td colspan="4">
                        <div class="form-group">
                          <label for="buyer_comment">Enter Feedback</label>
                          <textarea class="form-control" id="buyer_comment" rows="3" name='buyer_comment'></textarea>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td colspan="4">
                        <div class="form-group">
                          <label for="buyer_rating">Rating</label>
                          <select id="buyer_rating" class="form-control" name='buyer_rating'>
                            <option selected>10</option>
                            <option>9</option>
                            <option>8</option>
                            <option>7</option>
                            <option>6</option>
                            <option>5</option>
                            <option>4</option>
                            <option>3</option>
                            <option>2</option>
                            <option>1</option>
                          </select>
                        </div>
                      </td>
                    </tr>
                    {% endif %}
                    <tr>
                      <td colspan="4">
                        <button type="submit" class="btn btn-outline-info">Submit Feedback</button>
                      </td>
                    </tr>
                  </form>
              {% elif is_active %}
              <tr>  
                <td colspan="2">
                  <ul class="nav nav-tabs mb-3 justify-content-center" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active" id="pills-high-bid-tab" data-toggle="pill" href="#pills-high-bids" role="tab" aria-controls="pills-high-bids" aria-selected="true">Highest Bid</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="pills-all-bids-tab" data-toggle="pill" href="#pills-all-bids" role="tab" aria-controls="pills-all-bids" aria-selected="false">All Bids</a>
                    </li>
                  </ul>
              
                  <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-high-bids" role="tabpanel" aria-labelledby="pills-high-bids-tab">
                        <strong>Highest Bid : </strong> {{ "$%.2f" | format(highestBid['HighestBid'] | float) }}
                    </div>
                    <div class="tab-pane fade" id="pills-all-bids" role="tabpanel" aria-labelledby="pills-all-bids-tab">
                      <strong>All Bids</strong>
                      <table>
                        <tr>
                          <th>Buyer ID</th>
                          <th>Bidding Time</th>
                          <th>Price</th>
                        </tr>
                        {% for buyer in bidderList %}
                          <tr>
                            <td> <a href="/profile/{{ buyer['BuyerID'] }}">{{ buyer['BuyerID']}}</a> </td>
                            <td> {{ buyer['BiddingTime']}}</td>
                            <td> {{ "$%.2f" | format(buyer['Price'] | float) }}</td>
                          </tr>
                        {% endfor %}
                      </table>
                    </div>
                  </div>

                </td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
          
        {% if not is_Feedback and is_active %}
        <form method="post" action="/product/{{ prod.ItemID }}">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Bid Value : $</span>
            </div>
            <input type="number" class="form-control rounded mx-sm-3" name="bidValue" min = "{{ highestBid.HighestBid }}" 
            value="{{ highestBid.HighestBid }}" step="{{ prod.BidIncrement }}" onkeydown="return false"/>
            <div class="input-group-append">
              <button type="submit" class="btn btn-outline-primary">Bid Now</button>
            </div>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

project/website/templates/search_category.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 
{% block content %}
  <h1> Item List of {{categoryName}} Category</h1>
  <div class="container-fluid">
    <div class="row no-gutters">
      <div style="display: block;
      max-width: -moz-fit-content;
      max-width: fit-content;
      margin: 0 auto;
      overflow-x: auto;
      white-space: nowrap;">
        <div class="table-responsive">
          <table class="table">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Starting Bid</th>
                    <th>Bid Increment</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Seller ID</th>
                    <th>Bidding Link</th>
                </tr>
                {% for i in ItemTuple %}
                    <tr>
                        <td> {{ i[0] }}</td>
                        <td> {{ i[1] }}</td>
                        <td> {{ i[2] }}</td>
                        <td> {{ "$%.2f" | format(i[4]| float) }}</td>
                        <td> {{ "$%.2f" | format(i[5]| float) }}</td>
                        <td> {{ i[6] }}</td>
                        <td> {{ i[7] }}</td>
                        <td> {{ i[8] }}</td>
                        <td> <a href="http://127.0.0.1:5000/product/{{i[0]}}">Product Details</a></td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

project/website/templates/sign_up_success.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}
{% block content %}
    <h1>Registration completed!</h1>
    <p>Your member ID is {{ session['login.id'] }}. Please use this to log in from now on.</p>
{% endblock %}